import { mkdir, readFile, writeFile } from "node:fs/promises";
import { Agent, CursorAgentError } from "@cursor/sdk";

const AUDIT_PATH = "logs/npm-audit.json";
const SUGGESTIONS_PATH = "logs/npm-audit-suggestions.md";

function suggestionsMarkdown(body: string): string {
  return `# npm audit suggestions

Generated by \`scripts/pr-audit-agent.ts\` using \`@cursor/sdk\` (\`Agent.prompt\`).
The agent is asked for advice only; this script writes the file.

${body.trim()}
`;
}

async function main(): Promise<void> {
  await mkdir("logs", { recursive: true });
  const auditJson = await readFile(AUDIT_PATH, "utf8");
  const apiKey = process.env.CURSOR_TO_GIT_API_KEY?.trim();

  if (!apiKey) {
    await writeFile(
      SUGGESTIONS_PATH,
      suggestionsMarkdown("Skipped: repository secret `CURSOR_TO_GIT_API_KEY` is not set."),
    );
    console.log("CURSOR_TO_GIT_API_KEY missing; wrote skip note to", SUGGESTIONS_PATH);
    return;
  }

  const prompt = `You are reviewing npm audit findings for SmartShop, an npm workspaces monorepo (root plus infra, packages/shared, services/api, web).

Do not edit files, run shell commands that change the tree, or apply upgrades. Return markdown suggestions only.

npm audit JSON:
\`\`\`json
${auditJson}
\`\`\`

Include:
- A short risk summary for this repo (dev-only vs production runtime).
- Which packages to bump, and whether a major / --force upgrade is required.
- Safer alternatives if a force upgrade would break CDK or React Router v6.
`;

  try {
    const result = await Agent.prompt(prompt, {
      apiKey,
      model: { id: "composer-2.5" },
      local: { cwd: process.cwd() },
    });
    console.log("agent run", result.id, result.status);
    const text = result.result?.trim() || result.error?.message || "(no suggestion text)";
    await writeFile(
      SUGGESTIONS_PATH,
      suggestionsMarkdown(`- status: \`${result.status}\`\n- run id: \`${result.id}\`\n\n${text}`),
    );
  } catch (caught) {
    const message =
      caught instanceof CursorAgentError
        ? `${caught.message} (retryable=${caught.isRetryable})`
        : caught instanceof Error
          ? caught.message
          : String(caught);
    console.error("agent startup failed:", message);
    await writeFile(SUGGESTIONS_PATH, suggestionsMarkdown(`Agent did not start:\n\n${message}`));
  }
}

await main();
