/**
 * 1) Send npm audit + CodeQL findings to Cursor for recommendations → PR comment
 * 2) Optionally invoke Cursor again to apply code fixes
 * 3) Push only changed files to smartshop-security-fixes on branch pr-<PR_NUMBER>
 */
import { spawnSync } from "node:child_process";
import { appendFile, copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { Agent, CursorAgentError } from "@cursor/sdk";

const AUDIT_PATH = process.env.NPM_AUDIT_PATH?.trim() || "logs/npm-audit.json";
const SECURITY_FIXES_REPO =
  process.env.SECURITY_FIXES_REPO?.trim() || "jaganathan-vinod/smartshop-security-fixes";
const APPLY_FIXES = (process.env.APPLY_SECURITY_FIXES ?? "true").trim().toLowerCase() !== "false";
const MAX_AUDIT_CHARS = 60_000;
const MAX_CODEQL_CHARS = 40_000;
const MAX_COMMENT_CHARS = 60_000;
const MAX_RECOMMENDATION_CHARS = 40_000;

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}\n…(truncated ${text.length - max} chars)`;
}

function run(
  command: string,
  args: string[],
  options?: { cwd?: string; env?: NodeJS.ProcessEnv },
): { ok: boolean; stdout: string; stderr: string; status: number | null } {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    cwd: options?.cwd,
    env: { ...process.env, ...options?.env },
    maxBuffer: 10 * 1024 * 1024,
  });
  return {
    ok: result.status === 0,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
    status: result.status,
  };
}

function runGh(args: string[]): { ok: boolean; stdout: string; stderr: string } {
  const result = run("gh", args);
  return { ok: result.ok, stdout: result.stdout, stderr: result.stderr };
}

function commentMarkdown(body: string): string {
  return `## Security recommendations (Cursor)

Generated by \`scripts/pr-audit-agent.ts\` from **npm audit** + **CodeQL** findings.
Advice only in this comment — code fixes (if any) are pushed to \`${SECURITY_FIXES_REPO}\`.

${body.trim()}
`;
}

function fixesCommentMarkdown(body: string): string {
  return `## Security fixes push (Cursor)

${body.trim()}
`;
}

async function sleep(ms: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

function summarizeAlerts(alerts: unknown[]): string {
  const slim = alerts.map((raw) => {
    const alert = raw as {
      number?: number;
      state?: string;
      rule?: { id?: string; description?: string; severity?: string; name?: string };
      most_recent_instance?: {
        ref?: string;
        location?: { path?: string; start_line?: number; end_line?: number };
        message?: { text?: string };
      };
      html_url?: string;
    };
    return {
      number: alert.number,
      state: alert.state,
      ruleId: alert.rule?.id,
      ruleName: alert.rule?.name,
      severity: alert.rule?.severity,
      description: alert.rule?.description,
      path: alert.most_recent_instance?.location?.path,
      startLine: alert.most_recent_instance?.location?.start_line,
      message: alert.most_recent_instance?.message?.text,
      ref: alert.most_recent_instance?.ref,
      url: alert.html_url,
    };
  });
  return JSON.stringify(slim, null, 2);
}

async function listAlerts(repo: string, query: string): Promise<unknown[] | null> {
  const listed = runGh(["api", `repos/${repo}/code-scanning/alerts?${query}`]);
  if (!listed.ok) {
    console.warn("code-scanning alerts fetch failed:", query, listed.stderr.trim());
    return null;
  }
  try {
    const parsed = JSON.parse(listed.stdout) as unknown;
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    console.warn("code-scanning alerts response was not JSON for", query);
    return null;
  }
}

async function resolvePrNumber(): Promise<string | undefined> {
  const fromEnv = process.env.PR_NUMBER?.trim();
  if (fromEnv) return fromEnv;

  if (!process.env.GITHUB_EVENT_PATH) return undefined;
  try {
    const event = JSON.parse(await readFile(process.env.GITHUB_EVENT_PATH, "utf8")) as {
      pull_request?: { number?: number };
      number?: number;
    };
    const value = event.pull_request?.number ?? event.number;
    return value != null ? String(value) : undefined;
  } catch {
    return undefined;
  }
}

async function fetchCodeqlAlerts(): Promise<string> {
  const repo = process.env.GITHUB_REPOSITORY?.trim();
  if (!repo) {
    return JSON.stringify({ skipped: true, reason: "GITHUB_REPOSITORY is not set" });
  }

  const prNumber = await resolvePrNumber();
  const headRef = process.env.GITHUB_HEAD_REF?.trim();
  const queries: string[] = [];

  if (prNumber) {
    queries.push(`pr=${encodeURIComponent(prNumber)}&per_page=100`);
    queries.push(`ref=${encodeURIComponent(`refs/pull/${prNumber}/merge`)}&per_page=100`);
    queries.push(`ref=${encodeURIComponent(`refs/pull/${prNumber}/head`)}&per_page=100`);
  }
  if (headRef) {
    queries.push(`ref=${encodeURIComponent(`refs/heads/${headRef}`)}&per_page=100`);
    queries.push(`ref=${encodeURIComponent(headRef)}&per_page=100`);
  }
  queries.push("state=open&per_page=100");

  const attempts = 5;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    for (const query of queries) {
      const alerts = await listAlerts(repo, query);
      if (alerts && alerts.length > 0) {
        console.log(
          `Fetched ${alerts.length} CodeQL alert(s) via ${query} (attempt ${attempt})`,
        );
        return summarizeAlerts(alerts);
      }
    }
    if (attempt < attempts) {
      const waitMs = attempt * 5_000;
      console.log(`No CodeQL alerts yet; retrying in ${waitMs}ms (attempt ${attempt}/${attempts})`);
      await sleep(waitMs);
    }
  }

  return JSON.stringify({
    alerts: [],
    note: "No CodeQL alerts returned from the API after retries.",
    tried: queries,
  });
}

async function postPrComment(body: string): Promise<void> {
  const number = await resolvePrNumber();
  if (!number) {
    console.log("No PR number; skipping gh pr comment");
    return;
  }

  const payload = truncate(body, MAX_COMMENT_CHARS);
  await mkdir("logs", { recursive: true });
  const bodyFile = "logs/cursor-security-comment.md";
  await writeFile(bodyFile, payload, "utf8");

  const commented = runGh(["pr", "comment", number, "--body-file", bodyFile]);
  if (!commented.ok) {
    throw new Error(`gh pr comment failed: ${commented.stderr.trim() || commented.stdout.trim()}`);
  }
  console.log("Posted PR comment on #" + number);
}

async function writeStepSummary(body: string): Promise<void> {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY?.trim();
  if (!summaryPath) return;
  await appendFile(summaryPath, `${body.trim()}\n`, "utf8");
}

function changedFiles(): string[] {
  const tracked = run("git", ["diff", "--name-only", "--diff-filter=ACMR"]);
  const untracked = run("git", ["ls-files", "--others", "--exclude-standard"]);
  const names = new Set<string>();
  for (const line of `${tracked.stdout}\n${untracked.stdout}`.split("\n")) {
    const name = line.trim();
    if (!name) continue;
    if (name.startsWith("logs/")) continue;
    if (name.startsWith("node_modules/")) continue;
    names.add(name);
  }
  return [...names].sort();
}

function restoreWorkingTree(): void {
  run("git", ["checkout", "--", "."]);
  run("git", ["clean", "-fd", "--exclude=logs", "--exclude=node_modules"]);
}

async function applyFixesWithCursor(
  apiKey: string,
  recommendations: string,
  codeqlJson: string,
): Promise<{ files: string[]; agentStatus: string; agentId?: string; error?: string }> {
  const agent = await Agent.create({
    apiKey,
    model: { id: "composer-2.5" },
    local: { cwd: process.cwd() },
  });

  try {
    const prompt = `You are fixing security findings for SmartShop.

Apply concrete code fixes for the CodeQL / code-scanning issues below.
Use the recommendations as guidance.

Rules:
- Edit source files in this workspace to remediate the alerts (e.g. parameterized SQL, basic rate limiting).
- Prefer minimal, focused changes. Do not bump major npm dependencies.
- Do not commit, push, or create pull requests.
- Do not modify .github/workflows or CI scripts.
- If a finding is in a deliberate sample under samples/, still fix that sample so scanners pass.
- When done, briefly list the files you changed.

## Recommendations
${truncate(recommendations, MAX_RECOMMENDATION_CHARS)}

## CodeQL alerts JSON
\`\`\`json
${codeqlJson}
\`\`\`
`;

    const runHandle = await agent.send(prompt);
    const result = await runHandle.wait();
    const files = changedFiles();
    return {
      files,
      agentStatus: result.status,
      agentId: result.id,
      error: result.status === "error" ? result.error?.message || "agent run error" : undefined,
    };
  } finally {
    await agent[Symbol.asyncDispose]();
  }
}

async function pushChangedFilesToSecurityFixesRepo(
  files: string[],
  prNumber: string,
): Promise<{ branch: string; url: string; commit?: string }> {
  const token =
    process.env.SECURITY_FIXES_TOKEN?.trim() ||
    process.env.GH_TOKEN?.trim() ||
    process.env.GITHUB_TOKEN?.trim();
  if (!token) {
    throw new Error(
      "SECURITY_FIXES_TOKEN is not set. Add a PAT with contents:write on " + SECURITY_FIXES_REPO,
    );
  }
  if (files.length === 0) {
    throw new Error("No changed files to push");
  }

  const branch = `pr-${prNumber}`;
  const remoteUrl = `https://x-access-token:${token}@github.com/${SECURITY_FIXES_REPO}.git`;
  const work = await mkdtemp(join(tmpdir(), "smartshop-security-fixes-"));
  const sourceRoot = process.cwd();

  try {
    const clone = run("git", ["clone", "--depth", "1", remoteUrl, work]);
    if (!clone.ok) {
      console.warn("clone failed; initializing repo:", clone.stderr.trim() || clone.stdout.trim());
      await rm(work, { recursive: true, force: true });
      await mkdir(work, { recursive: true });
      run("git", ["init", "-b", "main"], { cwd: work });
      run("git", ["remote", "add", "origin", remoteUrl], { cwd: work });
      await writeFile(
        join(work, "README.md"),
        `# smartshop-security-fixes\n\nAutomated security fix branches from SmartShop PRs.\n`,
        "utf8",
      );
      run("git", ["add", "README.md"], { cwd: work });
      run(
        "git",
        [
          "-c",
          "user.name=github-actions[bot]",
          "-c",
          "user.email=41898282+github-actions[bot]@users.noreply.github.com",
          "commit",
          "-m",
          "chore: initialize repository",
        ],
        { cwd: work },
      );
      const initPush = run("git", ["push", "-u", "origin", "HEAD:main"], { cwd: work });
      if (!initPush.ok) {
        throw new Error(
          `failed to initialize ${SECURITY_FIXES_REPO}: ${initPush.stderr.trim() || initPush.stdout.trim()}`,
        );
      }
    }

    // Create/reset the PR branch from current default tip.
    run("git", ["fetch", "origin"], { cwd: work });
    const checkout = run("git", ["checkout", "-B", branch, "origin/main"], { cwd: work });
    if (!checkout.ok) {
      run("git", ["checkout", "-B", branch], { cwd: work });
    }

    for (const file of files) {
      const from = join(sourceRoot, file);
      const to = join(work, file);
      await mkdir(dirname(to), { recursive: true });
      await copyFile(from, to);
    }

    // Preserve a small manifest of what was mirrored from which PR.
    await mkdir(join(work, "meta"), { recursive: true });
    await writeFile(
      join(work, "meta", `pr-${prNumber}.json`),
      JSON.stringify(
        {
          sourceRepo: process.env.GITHUB_REPOSITORY,
          sourcePr: Number(prNumber),
          sourceRef: process.env.GITHUB_HEAD_REF,
          files,
          generatedAt: new Date().toISOString(),
        },
        null,
        2,
      ) + "\n",
      "utf8",
    );

    run("git", ["add", "-A"], { cwd: work });
    const diff = run("git", ["diff", "--cached", "--quiet"], { cwd: work });
    if (diff.status === 0) {
      return {
        branch,
        url: `https://github.com/${SECURITY_FIXES_REPO}/tree/${branch}`,
      };
    }

    const commit = run(
      "git",
      [
        "-c",
        "user.name=github-actions[bot]",
        "-c",
        "user.email=41898282+github-actions[bot]@users.noreply.github.com",
        "commit",
        "-m",
        `fix: security remediations from SmartShop PR #${prNumber}`,
      ],
      { cwd: work },
    );
    if (!commit.ok) {
      throw new Error(`commit failed: ${commit.stderr.trim() || commit.stdout.trim()}`);
    }

    const push = run("git", ["push", "-u", "origin", `HEAD:${branch}`, "--force"], { cwd: work });
    if (!push.ok) {
      throw new Error(`push failed: ${push.stderr.trim() || push.stdout.trim()}`);
    }

    const sha = run("git", ["rev-parse", "HEAD"], { cwd: work }).stdout.trim();
    return {
      branch,
      url: `https://github.com/${SECURITY_FIXES_REPO}/tree/${encodeURIComponent(branch)}`,
      commit: sha,
    };
  } finally {
    await rm(work, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  const auditJson = truncate(await readFile(AUDIT_PATH, "utf8"), MAX_AUDIT_CHARS);
  const codeqlJson = truncate(await fetchCodeqlAlerts(), MAX_CODEQL_CHARS);
  const apiKey = process.env.CURSOR_TO_GIT_API_KEY?.trim();

  if (!apiKey) {
    const skipped = commentMarkdown(
      "Skipped: repository secret `CURSOR_TO_GIT_API_KEY` is not set.",
    );
    await writeStepSummary(skipped);
    await postPrComment(skipped);
    return;
  }

  const recommendPrompt = `You are reviewing security findings for SmartShop, an npm workspaces monorepo
(root plus infra, packages/shared, services/api, services/assistant, web).

IMPORTANT:
- Recommendations only. Do NOT edit files, run shell commands, apply upgrades, or invent patches.
- Do NOT propose committing anything back to the PR.
- Return concise markdown a human can act on later.

## npm audit JSON
\`\`\`json
${auditJson}
\`\`\`

## CodeQL / code scanning alerts JSON
\`\`\`json
${codeqlJson}
\`\`\`

Include:
1. Short overall risk summary (dev-only vs production/runtime).
2. npm audit: which packages to bump, whether a major/--force upgrade is needed, and safer alternatives if CDK or React Router v6 would break.
3. CodeQL: each alert in plain language, severity, likely file/location, and recommended remediation (parameterized queries, etc.) — still advice only.
4. Suggested priority order (what to fix first).
`;

  let recommendationsText: string;
  let body: string;
  try {
    const result = await Agent.prompt(recommendPrompt, {
      apiKey,
      model: { id: "composer-2.5" },
      local: { cwd: process.cwd() },
    });
    console.log("recommend agent run", result.id, result.status);
    recommendationsText = result.result?.trim() || result.error?.message || "(no suggestion text)";
    body = commentMarkdown(
      `- status: \`${result.status}\`\n- run id: \`${result.id}\`\n\n${recommendationsText}`,
    );
  } catch (caught) {
    const message =
      caught instanceof CursorAgentError
        ? `${caught.message} (retryable=${caught.isRetryable})`
        : caught instanceof Error
          ? caught.message
          : String(caught);
    console.error("recommend agent startup failed:", message);
    recommendationsText = `Agent did not start:\n\n${message}`;
    body = commentMarkdown(recommendationsText);
  }

  await writeStepSummary(body);
  await postPrComment(body);

  if (!APPLY_FIXES) {
    console.log("APPLY_SECURITY_FIXES=false; skipping fix agent + push");
    return;
  }

  const prNumber = await resolvePrNumber();
  if (!prNumber) {
    const note = fixesCommentMarkdown("Skipped fixes push: no PR number available.");
    await writeStepSummary(note);
    await postPrComment(note);
    return;
  }

  let fixSummary: string;
  try {
    const applied = await applyFixesWithCursor(apiKey, recommendationsText, codeqlJson);
    console.log("fix agent", applied.agentId, applied.agentStatus, "files:", applied.files);

    if (applied.error) {
      fixSummary = fixesCommentMarkdown(
        `Fix agent finished with status \`${applied.agentStatus}\`.\n\n${applied.error}`,
      );
    } else if (applied.files.length === 0) {
      fixSummary = fixesCommentMarkdown(
        `Fix agent (\`${applied.agentStatus}\`, run \`${applied.agentId ?? "n/a"}\`) made no file changes.`,
      );
    } else {
      const pushed = await pushChangedFilesToSecurityFixesRepo(applied.files, prNumber);
      fixSummary = fixesCommentMarkdown(
        [
          `- fix agent status: \`${applied.agentStatus}\``,
          `- fix agent run: \`${applied.agentId ?? "n/a"}\``,
          `- target repo: \`${SECURITY_FIXES_REPO}\``,
          `- branch: \`${pushed.branch}\``,
          pushed.commit ? `- commit: \`${pushed.commit}\`` : null,
          `- files:`,
          ...applied.files.map((f) => `  - \`${f}\``),
          `- browse: ${pushed.url}`,
        ]
          .filter(Boolean)
          .join("\n"),
      );
    }
  } catch (caught) {
    const message = caught instanceof Error ? caught.message : String(caught);
    console.error("fix/push failed:", message);
    fixSummary = fixesCommentMarkdown(`Fix agent / push failed:\n\n\`\`\`\n${message}\n\`\`\``);
  } finally {
    // Keep the SmartShop PR branch clean — fixes live only in security-fixes repo.
    restoreWorkingTree();
  }

  await writeStepSummary(fixSummary);
  await postPrComment(fixSummary);
}

main().catch(async (caught: unknown) => {
  const message = caught instanceof Error ? caught.message : String(caught);
  console.error(message);
  const body = commentMarkdown(`Agent script crashed:\n\n${message}`);
  try {
    await writeStepSummary(body);
    await postPrComment(body);
  } catch (postError) {
    console.error("failed to post failure comment:", postError);
  }
  process.exitCode = 1;
});
