/**
 * Sends npm audit + CodeQL findings to Cursor for recommendations only,
 * then posts the reply as a PR comment (no commits, no code changes).
 */
import { spawnSync } from "node:child_process";
import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { Agent, CursorAgentError } from "@cursor/sdk";

const AUDIT_PATH = process.env.NPM_AUDIT_PATH?.trim() || "logs/npm-audit.json";
const MAX_AUDIT_CHARS = 60_000;
const MAX_CODEQL_CHARS = 40_000;
const MAX_COMMENT_CHARS = 60_000;

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}\n…(truncated ${text.length - max} chars)`;
}

function runGh(args: string[]): { ok: boolean; stdout: string; stderr: string } {
  const result = spawnSync("gh", args, {
    encoding: "utf8",
    env: process.env,
    maxBuffer: 10 * 1024 * 1024,
  });
  return {
    ok: result.status === 0,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

function commentMarkdown(body: string): string {
  return `## Security recommendations (Cursor)

Generated by \`scripts/pr-audit-agent.ts\` from **npm audit** + **CodeQL** findings.
Advice only — no code changes were applied.

${body.trim()}
`;
}

async function fetchCodeqlAlerts(): Promise<string> {
  const repo = process.env.GITHUB_REPOSITORY?.trim();
  const headRef = process.env.GITHUB_HEAD_REF?.trim();
  if (!repo) {
    return JSON.stringify({ skipped: true, reason: "GITHUB_REPOSITORY is not set" });
  }

  const refsToTry = headRef
    ? [`refs/heads/${headRef}`, headRef]
    : [process.env.GITHUB_REF?.trim()].filter(Boolean) as string[];

  for (const ref of refsToTry) {
    const listed = runGh([
      "api",
      `repos/${repo}/code-scanning/alerts?state=open&ref=${encodeURIComponent(ref)}&per_page=100`,
    ]);
    if (!listed.ok) {
      console.warn("code-scanning alerts fetch failed for", ref, listed.stderr.trim());
      continue;
    }
    try {
      const parsed = JSON.parse(listed.stdout) as unknown;
      if (Array.isArray(parsed) && parsed.length > 0) {
        return JSON.stringify(parsed, null, 2);
      }
      if (Array.isArray(parsed)) {
        console.log("No open CodeQL alerts for ref", ref);
      }
    } catch {
      return listed.stdout;
    }
  }

  // Fall back to all open alerts for the repo if ref-scoped query is empty/unavailable.
  const allOpen = runGh([
    "api",
    `repos/${repo}/code-scanning/alerts?state=open&per_page=100`,
  ]);
  if (!allOpen.ok) {
    return JSON.stringify({
      error: "Failed to fetch CodeQL alerts",
      detail: allOpen.stderr.trim() || allOpen.stdout.trim(),
    });
  }
  return allOpen.stdout;
}

async function resolvePrNumber(): Promise<string | undefined> {
  const fromEnv = process.env.PR_NUMBER?.trim();
  if (fromEnv) return fromEnv;

  if (!process.env.GITHUB_EVENT_PATH) return undefined;
  try {
    const event = JSON.parse(await readFile(process.env.GITHUB_EVENT_PATH, "utf8")) as {
      pull_request?: { number?: number };
      number?: number;
    };
    const value = event.pull_request?.number ?? event.number;
    return value != null ? String(value) : undefined;
  } catch {
    return undefined;
  }
}

async function postPrComment(body: string): Promise<void> {
  const number = await resolvePrNumber();
  if (!number) {
    console.log("No PR number; skipping gh pr comment");
    return;
  }

  const payload = truncate(body, MAX_COMMENT_CHARS);
  await mkdir("logs", { recursive: true });
  const bodyFile = "logs/cursor-security-comment.md";
  await writeFile(bodyFile, payload, "utf8");

  const commented = runGh(["pr", "comment", number, "--body-file", bodyFile]);
  if (!commented.ok) {
    throw new Error(`gh pr comment failed: ${commented.stderr.trim() || commented.stdout.trim()}`);
  }
  console.log("Posted PR comment on #" + number);
}

async function writeStepSummary(body: string): Promise<void> {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY?.trim();
  if (!summaryPath) return;
  await appendFile(summaryPath, `${body.trim()}\n`, "utf8");
}

async function main(): Promise<void> {
  const auditJson = truncate(await readFile(AUDIT_PATH, "utf8"), MAX_AUDIT_CHARS);
  const codeqlJson = truncate(await fetchCodeqlAlerts(), MAX_CODEQL_CHARS);
  const apiKey = process.env.CURSOR_TO_GIT_API_KEY?.trim();

  if (!apiKey) {
    const skipped = commentMarkdown(
      "Skipped: repository secret `CURSOR_TO_GIT_API_KEY` is not set.",
    );
    await writeStepSummary(skipped);
    await postPrComment(skipped);
    return;
  }

  const prompt = `You are reviewing security findings for SmartShop, an npm workspaces monorepo
(root plus infra, packages/shared, services/api, services/assistant, web).

IMPORTANT:
- Recommendations only. Do NOT edit files, run shell commands, apply upgrades, or invent patches.
- Do NOT propose committing anything back to the PR.
- Return concise markdown a human can act on later.

## npm audit JSON
\`\`\`json
${auditJson}
\`\`\`

## CodeQL / code scanning alerts JSON
\`\`\`json
${codeqlJson}
\`\`\`

Include:
1. Short overall risk summary (dev-only vs production/runtime).
2. npm audit: which packages to bump, whether a major/--force upgrade is needed, and safer alternatives if CDK or React Router v6 would break.
3. CodeQL: each alert in plain language, severity, likely file/location, and recommended remediation (parameterized queries, etc.) — still advice only.
4. Suggested priority order (what to fix first).
`;

  let body: string;
  try {
    const result = await Agent.prompt(prompt, {
      apiKey,
      model: { id: "composer-2.5" },
      local: { cwd: process.cwd() },
    });
    console.log("agent run", result.id, result.status);
    const text = result.result?.trim() || result.error?.message || "(no suggestion text)";
    body = commentMarkdown(`- status: \`${result.status}\`\n- run id: \`${result.id}\`\n\n${text}`);
  } catch (caught) {
    const message =
      caught instanceof CursorAgentError
        ? `${caught.message} (retryable=${caught.isRetryable})`
        : caught instanceof Error
          ? caught.message
          : String(caught);
    console.error("agent startup failed:", message);
    body = commentMarkdown(`Agent did not start:\n\n${message}`);
  }

  await writeStepSummary(body);
  await postPrComment(body);
}

main().catch(async (caught: unknown) => {
  const message = caught instanceof Error ? caught.message : String(caught);
  console.error(message);
  const body = commentMarkdown(`Agent script crashed:\n\n${message}`);
  try {
    await writeStepSummary(body);
    await postPrComment(body);
  } catch (postError) {
    console.error("failed to post failure comment:", postError);
  }
  process.exitCode = 1;
});
